Professor & Project page
JFleming4/FourthYearProjectSite pull request #46
Opened 2018-03-21 15:38 UTC by noahsegal

Added basic pages for the Professor and the Project.
- Nonfunctional buttons for creating/archiving/deleting projects on the Professor page
- Nonfunctional buttons for accessing the availability page (@JFleming4 will link)

2018-03-21 19:55 UTC, DerekStride requested changes
Can you add controller tests?

2018-03-21 19:55 UTC, DerekStride commented on src/main/java/app/controllers/ProjectController.java
> +        Project project = projectRepository.findFirstByOrderById();
Can you make this lookup by id, rather than just grabbing the first one?

2018-03-21 19:55 UTC, DerekStride commented on src/main/java/app/controllers/ProfessorController.java
> +        Professor professor = professorRepository.findFirstByOrderById();
Can you make this lookup by id, rather than just grabbing the first one?

2018-03-21 19:57 UTC, DerekStride commented on src/main/resources/templates/professor.html
> +        <button>Delete</button>
It shouldn't be too hard to implement these buttons.

2018-03-22 11:28 UTC, JFleming4 approved these changes
I agree with Dereks Comments but I'm moving them to a new issue for the sake of completing work related to yours

2018-03-22 11:29 UTC, merged